// AUTOGENERATED FILE - DO NOT EDIT

var pt = window.PropTypes;
var pk = window['dash_react_flow'];

pk.DashReactFlow.propTypes = {initial_nodes:pt.arrayOf(pt.shape({id:pt.string,position:pt.shape({x:pt.number,y:pt.number}),data:pt.objectOf(pt.any)})),
 initial_edges:pt.arrayOf(pt.shape({id:pt.string,source:pt.string,target:pt.string})),
 id:pt.string,
 setProps:pt.any};
